server:
  port: 8889
  servlet:
    context-path: /msapp

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multiseafoods?characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    username: root


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.mulitseafoods.msapp.entity


